"""Three-pane workspace; all actions delegate to the existing application."""
import tkinter as tk
from tkinter import ttk
from ui_theme import Card,artwork,PAPER,WHITE,INK,MUTED,SAGE,BLUE,GOLD,GREEN

def label(parent,text,**kwargs):
    return ttk.Label(parent,text=text,**kwargs)

def section(parent,number,title,subtitle):
    label(parent,number+'  /  '+title,style='Section.TLabel').pack(anchor='w',pady=(4,6))
    label(parent,subtitle,style='Muted.TLabel',wraplength=235).pack(anchor='w',pady=(0,8))

class ScrollPanel(ttk.Frame):
    def __init__(self,parent):
        super().__init__(parent)
        self.canvas=tk.Canvas(self,bg=WHITE,highlightthickness=0,bd=0)
        bar=ttk.Scrollbar(self,orient='vertical',command=self.canvas.yview)
        self.canvas.configure(yscrollcommand=bar.set);bar.pack(side='right',fill='y');self.canvas.pack(fill='both',expand=True)
        self.content=ttk.Frame(self.canvas);self.item=self.canvas.create_window(0,0,window=self.content,anchor='nw')
        self.content.bind('<Configure>',lambda e:self.canvas.configure(scrollregion=self.canvas.bbox('all')))
        self.canvas.bind('<Configure>',lambda e:self.canvas.itemconfigure(self.item,width=e.width))
        self.bind('<MouseWheel>',lambda e:self.canvas.yview_scroll(-int(e.delta/120),'units'))

def spin(parent,text,variable,low,high,callback):
    row=ttk.Frame(parent);row.pack(fill='x',pady=(4,12))
    label(row,text,style='Muted.TLabel').pack(side='left')
    widget=ttk.Spinbox(row,from_=low,to=high,textvariable=variable,width=5,command=callback)
    widget.pack(side='right');widget.bind('<Return>',lambda e:callback());widget.bind('<FocusOut>',lambda e:callback())
    return widget

def build_workspace(app,actor):
    root=app.root
    app.brand_photo=artwork(root,'site-icon.webp',(40,40),circle=True)
    app.mascot_photo=artwork(root,'mascot.webp',(120,120),circle=True)
    app.workspace_decoration=artwork(root,'auth-decoration-v1.png',(270,180))
    header=Card(root,padding=12);header.pack(fill='x',padx=16,pady=(12,10))
    bar=header.content
    tk.Label(bar,image=app.brand_photo,bg=WHITE).pack(side='left',padx=(2,12))
    identity=ttk.Frame(bar);identity.pack(side='left')
    label(identity,'OPC',font=('Arial',19,'bold')).pack(anchor='w')
    from release_info import PRODUCT, VERSION
    label(identity,PRODUCT+'  /  '+VERSION,style='Muted.TLabel').pack(anchor='w',pady=(2,0))
    ttk.Button(bar,text='退出登录',style='Quiet.TButton',command=app.logout).pack(side='right',padx=(8,0))
    ttk.Button(bar,text='使用规则与许可',style='Quiet.TButton',command=app.legal).pack(side='right',padx=(8,0))
    if actor['admin']:ttk.Button(bar,text='新增申请人',command=app.add_user).pack(side='right',padx=(12,0))
    if actor['admin']:ttk.Button(bar,text='印章 / 导出设置',style='Blue.TButton',command=app.settings).pack(side='right',padx=(8,0))
    account=ttk.Frame(bar);account.pack(side='right',padx=12)
    label(account,actor['name']+'  /  '+actor['id'],style='Section.TLabel').pack(anchor='e')
    label(account,'管理员' if actor['admin'] else '申请人',style='Muted.TLabel').pack(anchor='e',pady=(2,0))

    # Footer stays outside the expanding workspace, so actions never scroll away.
    dock=Card(root,padding=12);dock.pack(side='bottom',fill='x',padx=20,pady=(10,16))
    flow=ttk.Frame(dock.content);flow.pack(side='left')
    app.submit_button=ttk.Button(flow,text='确认并生成副本' if actor['admin'] else '提交审核',style='Primary.TButton',command=app.submit)
    app.submit_button.grid(row=0,column=0,padx=(0,6))
    app.approve_button=ttk.Button(flow,text='审核通过并盖章',style='Primary.TButton',command=app.approve)
    app.approve_button.grid(row=0,column=1,padx=(0,6))
    app.reject_button=ttk.Button(flow,text='退回',style='Danger.TButton',command=app.reject)
    app.reject_button.grid(row=0,column=2,padx=(0,6))
    app.undo_button=ttk.Button(dock.content,text='撤销上一步',command=app.undo);app.undo_button.pack(side='left',padx=6)
    app.withdraw_button=ttk.Button(dock.content,text='撤回 / 作废',style='Quiet.TButton',command=app.withdraw);app.withdraw_button.pack(side='left')
    app.export_button=ttk.Button(dock.content,text='导出副本  ↗',style='Primary.TButton',command=app.export);app.export_button.pack(side='right')
    app.save_as_button=ttk.Button(dock.content,text='另存为…',command=app.export_as);app.save_as_button.pack(side='right',padx=8)

    body=ttk.Frame(root,style='Paper.TFrame');body.pack(fill='both',expand=True,padx=20)
    body.columnconfigure(0,weight=0,minsize=240);body.columnconfigure(1,weight=1,minsize=320)
    body.columnconfigure(2,weight=0,minsize=278);body.rowconfigure(0,weight=1)
    leftcard=Card(body,width=248,padding=14);leftcard.grid(row=0,column=0,sticky='nsew',padx=(0,12));leftcard.pack_propagate(False)
    left=leftcard.content
    app.choose_button=ttk.Button(left,text='＋  选择 PDF',style='Primary.TButton',command=app.choose)
    app.choose_button.pack(fill='x',pady=(0,12))
    intro=tk.Frame(left,bg=SAGE);intro.pack(fill='x',pady=(0,16))
    app.side_mascot=artwork(root,'mascot.webp',(52,52),circle=True)
    tk.Label(intro,image=app.side_mascot,bg=SAGE).pack(side='left',padx=7,pady=9)
    words=tk.Frame(intro,bg=SAGE);words.pack(side='left',pady=8)
    tk.Label(words,text='认真确认，安心交付。',font=('Microsoft YaHei UI',9,'bold'),bg=SAGE,fg=GREEN,wraplength=135,justify='left').pack(anchor='w')
    tk.Label(words,text='小狗咪陪你处理文件',font=('Microsoft YaHei UI',8),bg=SAGE,fg=MUTED,wraplength=135,justify='left').pack(anchor='w',pady=(4,0))
    listing=ttk.Frame(left);listing.pack(fill='x',pady=(0,8))
    label(listing,'文件与申请',style='Section.TLabel').pack(side='left')
    app.count_text=tk.StringVar(value='0 份');label(listing,'',textvariable=app.count_text,style='Muted.TLabel').pack(side='right')
    table=ttk.Frame(left);table.pack(fill='both',expand=True)
    app.tree=ttk.Treeview(table,columns=('status','who'),displaycolumns=('status',),show='tree headings',height=5,selectmode='browse')
    app.tree.heading('#0',text='文件');app.tree.column('#0',width=140,minwidth=90,stretch=True)
    app.tree.heading('status',text='状态');app.tree.column('status',width=62,minwidth=62,stretch=False)
    app.tree.heading('who',text='工号');app.tree.column('who',width=60)
    yscroll=ttk.Scrollbar(table,orient='vertical',command=app.tree.yview)
    app.tree.configure(yscrollcommand=yscroll.set);yscroll.pack(side='right',fill='y');app.tree.pack(fill='both',expand=True)
    app.tree.bind('<<TreeviewSelect>>',app.select_request)
    ttk.Button(left,text='刷新列表',style='Quiet.TButton',command=app.refresh).pack(fill='x',pady=(12,8))
    app.detail=tk.StringVar(value='选择一份文件，查看申请详情。')
    label(left,'',textvariable=app.detail,style='Muted.TLabel',wraplength=210).pack(fill='x',pady=(4,2))

    previewcard=Card(body,padding=16);previewcard.grid(row=0,column=1,sticky='nsew',padx=(0,12))
    center=previewcard.content
    heading=ttk.Frame(center);heading.pack(fill='x',pady=(0,4))
    label(heading,'PDF 工作台',style='Section.TLabel').pack(side='left')
    app.document_state=tk.StringVar(value='尚未选择文件')
    label(heading,'',textvariable=app.document_state,style='Muted.TLabel').pack(side='right')
    app.document_title=tk.StringVar(value='选择文件后，在这里预览与定位。')
    app.file_title_label=label(center,'',textvariable=app.document_title,style='Muted.TLabel',wraplength=420)
    app.file_title_label.pack(anchor='w',pady=(3,12))
    pages=ttk.Frame(center);pages.pack(fill='x',pady=(0,12))
    ttk.Button(pages,text='←',width=2,command=lambda:app.turn(-1)).pack(side='left')
    app.page_text=tk.StringVar(value='等待文件')
    label(pages,'',textvariable=app.page_text).pack(side='left',padx=12)
    ttk.Button(pages,text='→',width=2,command=lambda:app.turn(1)).pack(side='left')
    app.mode_text=tk.StringVar(value='公章定位')
    label(pages,'',textvariable=app.mode_text,style='Muted.TLabel').pack(side='right')
    viewport=ttk.Frame(center);viewport.pack(fill='both',expand=True)
    app.canvas=tk.Canvas(viewport,bg=PAPER,highlightthickness=0,bd=0)
    horizontal=ttk.Scrollbar(viewport,orient='horizontal',command=app.canvas.xview);horizontal.pack(side='bottom',fill='x')
    scroll=ttk.Scrollbar(viewport,orient='vertical',command=app.canvas.yview);scroll.pack(side='right',fill='y')
    app.canvas.configure(yscrollcommand=scroll.set,xscrollcommand=horizontal.set);app.canvas.pack(fill='both',expand=True)
    app.canvas.bind('<Button-1>',app.place)
    app.canvas.bind('<MouseWheel>',lambda e:app.canvas.yview_scroll(-int(e.delta/120),'units'))
    app.canvas.bind('<Configure>',app.preview_resize)
    zoomrow=ttk.Frame(center);zoomrow.pack(fill='x',pady=(8,0))
    label(zoomrow,'预览缩放',style='Muted.TLabel').pack(side='left')
    zoom=ttk.Combobox(zoomrow,textvariable=app.zoom,values=('适合宽度','50%','75%','100%','125%','150%'),state='readonly',width=10)
    zoom.pack(side='right');zoom.bind('<<ComboboxSelected>>',lambda e:app.safe(app.draw))
    app.export_info=tk.StringVar(value='先预览，再确认生成。原件始终保留。')
    label(center,'',textvariable=app.export_info,style='Muted.TLabel',wraplength=450).pack(anchor='w',pady=(12,0))

    settingscard=Card(body,width=278,padding=14);settingscard.grid(row=0,column=2,sticky='nsew');settingscard.pack_propagate(False)
    right=settingscard.content
    label(right,'编辑与定位',style='Section.TLabel').pack(anchor='w',pady=(0,6))
    app.editor_hint=tk.StringVar(value='先选择 PDF，再设置盖章位置。')
    label(right,'',textvariable=app.editor_hint,style='Muted.TLabel',wraplength=235).pack(anchor='w',pady=(0,12))
    app.notebook=ttk.Notebook(right);app.notebook.pack(fill='both',expand=True)
    panels=[ScrollPanel(app.notebook) for _ in range(3)]
    seal,signature,text=[p.content for p in panels]
    for panel,title in zip(panels,('印章','签名','日期文字')):app.notebook.add(panel,text=title)
    app.notebook.bind('<<NotebookTabChanged>>',app.tool_tab_changed)
    label(seal,'01  /  自有印章',style='Section.TLabel').pack(anchor='w',pady=6)
    app.seal_name=tk.StringVar();label(seal,'',textvariable=app.seal_name,style='Muted.TLabel',wraplength=230).pack(anchor='w',pady=(0,6))
    app.stamp_label=tk.Label(seal,bg=WHITE);app.stamp_label.pack(pady=(4,8))
    app.update_seal_preview()
    app.seal_check=ttk.Checkbutton(seal,text='添加印章',variable=app.seal_enabled,command=app.redraw_markers)
    app.seal_check.pack(anchor='w')
    app.size=tk.StringVar(value='40')
    app.seal_size_input=spin(seal,'直径 / mm',app.size,15,63,app.resize_stamp)
    app.bottom_right_button=ttk.Button(seal,text='放在页面右下角',style='Blue.TButton',command=app.bottom_right)
    app.bottom_right_button.pack(fill='x',pady=6)
    ttk.Radiobutton(seal,text='点击页面放置公章',variable=app.placement,value='seal',command=app.update_mode).pack(anchor='w',pady=8)
    label(seal,'确认文件内容和盖章位置后，\n点击底部按钮生成副本。',style='Muted.TLabel').pack(anchor='w',pady=(8,0))
    section(signature,'02','本人签名','姓名生成楷书，或导入手写图片。')
    app.kai_button=ttk.Button(signature,text='姓名生成 · 楷书字样',style='Blue.TButton',command=app.make_signature)
    app.kai_button.pack(fill='x',pady=(0,10))
    app.import_button=ttk.Button(signature,text='导入手写签名图片',command=app.import_signature)
    app.import_button.pack(fill='x',pady=(0,12))
    label(signature,'图片会自动去白底，保留原笔迹。',style='Muted.TLabel',wraplength=230).pack(anchor='w',pady=(0,14))
    app.sig_check=ttk.Checkbutton(signature,text='添加签名',variable=app.sig_enabled,command=app.redraw_markers)
    app.sig_check.pack(anchor='w')
    app.signature_size_input=spin(signature,'宽度 / mm',app.sig_width,5,120,app.resize_signature)
    ttk.Radiobutton(signature,text='点击页面放置签名',variable=app.placement,value='signature',command=app.update_mode).pack(anchor='w',pady=8)
    label(signature,'生成或导入后，请先核对签名预览。',style='Muted.TLabel',wraplength=230).pack(anchor='w',pady=(12,0))
    section(text,'03','日期与文字','填日期、改文字，再点击页面定位。')
    app.labels=[];app.active_label=0;app.label_photos=[];app.text_font=tk.StringVar(value='12')
    app.date_button=ttk.Button(text,text='自动填今天 · 年月日',style='Blue.TButton',command=app.fill_date)
    app.date_button.pack(fill='x',pady=(0,10))
    app.text_button=ttk.Button(text,text='＋  添加日期或文字',command=app.add_text)
    app.text_button.pack(fill='x',pady=(0,12))
    app.text_size_input=spin(text,'文字字号',app.text_font,8,36,app.resize_text)
    selection=ttk.Frame(text);selection.pack(fill='x',pady=6)
    ttk.Button(selection,text='← 上一框',command=lambda:app.pick_text(-1)).pack(side='left')
    ttk.Button(selection,text='下一框 →',command=lambda:app.pick_text(1)).pack(side='right')
    app.text_info=tk.StringVar(value='未添加文字')
    label(text,'',textvariable=app.text_info,style='Muted.TLabel',wraplength=230).pack(anchor='w',pady=12)
    app.edit_text_button=ttk.Button(text,text='编辑当前文字',command=app.edit_text);app.edit_text_button.pack(fill='x',pady=5)
    app.remove_text_button=ttk.Button(text,text='删除当前文字',style='Quiet.TButton',command=app.remove_text);app.remove_text_button.pack(fill='x',pady=5)
    ttk.Radiobutton(text,text='点击页面放置文字',variable=app.placement,value='text',command=app.update_mode).pack(anchor='w',pady=8)
    label(right,'图形签章 · 本机处理',style='Muted.TLabel').pack(anchor='w',pady=(12,3))
    label(right,'原件与处理记录保留',style='Muted.TLabel').pack(anchor='w')
